### ISSUE TITLE
akkaのライセンス変更に対応する（？）

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text#1007]
- https://www.lightbend.com/blog/why-we-are-changing-the-license-for-akka
- https://github.com/akka/akka/pull/31561

今すこしakkaの記述があるが

https://github.com/scala-text/scala_text/blob/13ec0bd10057ac2572520eed2f420ad1953b5f0f/src/introduction-to-scala.md?plain=1#L80-L82

- 一般的なOSSではないことに一言触れる、追記する
- (OSS以外の注意を要するライブラリ紹介したくないなら？)バッサリakkaの記述削除
- ライブラリの紹介はしているが、OSSとは言ってない(scala text内部に嘘が書いてあるわけではない？)ので、まだ現状維持というか様子みる？

**Comment by kmizu** [comment]
Akkaについてはまだ反応を受けて状況変化する可能性があるので、いったん様子見でいいかなという意見です。この路線が確定したらさすがにOSSでないことははっきり言及した方が良さげです。

**Comment by kmizu** [comment]
memo: 2ヶ月くらい経ってもそのままの路線でいくなら、バッサリ切る方針で。
