### ISSUE TITLE
for 式の構文に if ガードがない

### ISSUE THREAD

**Issue by Javakky** [scala-text/scala_text#1010]
for 式の項で構文が以下のように記載されています。

```scala
for '(' (<ジェネレータ>;)+ ')' '<本体>' 
# <ジェネレータ> = x <- <式>
```

https://scala-text.github.io/scala_text/control-syntax.html#for%E5%BC%8F

しかし、下の項目で if ガードについての説明があるため、

```scala
# <ジェネレータ> = x <- <式> (if <条件式>)?
```

とした方が漏れがない気がします。

https://www.scala-lang.org/files/archive/spec/2.11/06-expressions.html#for-comprehensions-and-for-loops

**Comment by kmizu** [comment]
@Javakky 確かに抜けてました。追記でお願いしていいですか？
