### ISSUE TITLE
無効にしたepubのbuildを再度有効化

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text#1018]
これ (2022/9/12頃)
https://github.com/scala-text/scala_text/commit/f8dd77cb517ab43528d354021d39938f8d425367
の時点では通っているが、その後、何もしてないのに他のpull req含めて全部通っていない気がする

**Comment by kmizu** [comment]
確かになんか原因不明なところで `system.error()` 吐いて死んでますね。Pythonのモジュールに依存してて、そいつがQt必要だけどないぽい感じのエラー。epub/pdf生成しようとするところでなんか変なこと起きてるんですかね……。

![image](https://user-images.githubusercontent.com/97326/190960885-3542dc5c-2076-4430-8e8c-6aec7ba5a377.png)

**Comment by xuwei-k** [comment]
暫定対策入れたのでissueのtitle変えた
