### ISSUE TITLE
scala_textもくもく会@Discord議事録

### ISSUE THREAD

**Issue by kmizu** [scala-text/scala_text#1027]
もくもく会参加してない人が流れわかるようにIssue作ってみました。

**Comment by kmizu** [comment]
# 2022/10/10（月）議事録

- #1029 について： @kmizu が本日着手。
- #550 ： @rinotc さん不在のため進捗なし（？）。
- #1016 について： しばらく凍結状態ぽい。個人的には簡単な説明くらいは載せたほうがいい派なのだけど、意見がまとまっていないぽいので、あとで @kmizu がissueにコメントする。
- #864 について： @youta32449999 さんが本日着手。
- #991 と #1010 について： @Javakky さんが本日着手。
- 今後の進行について：
  - もくもく会の趣旨的に、話し合い自体は最低限にするのが良さそう
  - 冒頭で既存のissueとPRについて軽く話す。本日着手する作業について自己申告
  - 残り時間はもくもくと作業

**Comment by kmizu** [comment]
2022/12/05（月）議事録
- 出席者：@kmizu 
- 他に出席者がいないので #1029 について単独でもくもくと作業

**Comment by kmizu** [comment]
# 2023/01/16（月）議事録

- 出席者： @kmizu , @youta32449999  
- #1027 について： マージ済み。
- #1099 作成： @youta32449999 さんにアサイン。
- #1043について： @kmizu が引き続き作業。

cc @xuwei-k, @i10416, @rinotc, @youta32449999, @Javakky

**Comment by kmizu** [comment]
# 2023/01/30（月）議事録

- 出席者： @kmizu , @youta32449999
- #1099 について：作業中 by @youta32449999   
- #1100 について：作業中 by @kmizu 
cc @xuwei-k, @i10416, @rinotc, @youta32449999, @Javakky

**Comment by kmizu** [comment]
# 2023/04/10 議事録
- 出席者： @kmizu 
- 誤字脱字、表現のチェックを中心に修正してみる
  - ChatGPT APIを使う

**Comment by kmizu** [comment]
# 2023/7/10 議事録（敬称略）
- スキップ（ @kmizu が失念していたため）
転職間もなく色々ごたついているとはいえ、申し訳ありません 🙇 

## TrackのScalaトレーニングコースについて
cc @xuwei-k @youta32449999 @Javakky @rinotc @i10416 
- [Track](https://campaign.train.tracks.run/classes)のトレーニングコースにScalaの話を増設するという企画
  - JSAとして進める話
  - scala_textベースで練習問題などを増設
  - Trackを提供しているギブリーさんも乗り気
- @xuwei-k @rinotc @i10416 : こちら、話が勝手に進んだ感じになってすいません
- @Javakky @youta32449999 が一緒に作業をするメンバー
- 7月中に先方と一度ミーティング
  - 作業の進め方、実作業をするのは誰か、などなど

scala_textもくもく会が（私のせいで）迷走していたこともあり、いったんTrackの方のコース
をメインの目標にできればと思います。Trackのコース自体はプロプライエタリですが、気づいた点などを
scala_textの方に反映することはできるので、scala_textにとってもプラスになると思います

@rinotc @i10416 @xuwei-k もし、ご興味がおありの場合は Discordの方まで連絡いただければと思います

**Comment by xuwei-k** [comment]
最近もくもく会やってないし、必要になればre-open出来るので一旦close
