### ISSUE TITLE
[don't close] scala_textへの感想

### ISSUE THREAD

**Issue by kmizu** [scala-text/scala_text#235]
- このissueは本テキストへの感想を書くために追記onlyのissueです
  - 返信はあまり期待しないでください（返信するかもしれませんが）
- 誤字・脱字の報告、誤りの指摘・修正は別途issueを立てるかpull requestを送ってください
- 感想を書いてもらえると、本テキストのコミッタのモチベーションが上がるかもしれません

**Comment by cm-wada-yusuke** [comment]
クラスメソッド株式会社にてScala研修的テキスト使わせていただき、週一度のペース、約半年で読み終えました。まずは、とてもわかりやすく、かつScalaの面白さが存分に伝わる資料を作っていただき、そしてそれを公開していただいたことに感謝致します。以下、感想です。

* 章立ての構成が良く、「Scalaって何？」という参加者も問題なく順を追って学習することができた
* Scalaの魅力ともいえるコレクションとパターンマッチはやはり厚めに記載されており、力のいれようが参加者にも伝わった
* 結果、「文脈を型で表現し、型に対してパターンマッチをはじめとした操作を適用する」という考えが魅力に感じたようで、swiftやjavaにも欲しいという声が多数
* 成果として、Scalaプログラム（Play製のサーバサイドアプリ）のレビューが可能になる程度になり、開発者としても助かっている
* ただ、「型クラス」については「？」という感じでした。なので「紹介」にとどめておいたのは良かったかと思います。やはりここは言語の機能というより数学的な概念から把握したほうが近道になりうるレベルの話なので仕方ないといえば仕方ないかも
* 「Futureで非同期処理の文脈を扱える」「さらにflatMapで未来の戻り値に対する処理を書ける」「さらにfor-comprehensionでフラットに書ける」あたりが一番盛り上がりました

**Comment by kmizu** [comment]
wadaさん、まずは丁寧なご感想をありがとうございました。元々は、社内研修用のScalaテキストを
ブラッシュアップして公開したものではありますが、自由に使ってもらって感想をもっと欲しいと
思っており（あくまで私がそうであり、他の共著者がどうかはわかりませんが（汗））、とてもうれしいです。

* 一応、本テキストにおける私の役割としては、だいたい全体の1/2~2/3程度執筆、という感じでしょうか。

* 章立てについては、何度か初期の頃に何度か再構成したような記憶があるので、その点を評価していただけるのはとてもありがたいです。

* コレクションに関しては、Scalaの標準ライブラリで最も手厚い部分であるため、ここはかなり力を入れて書いた部分です。パターンマッチは割と普通に書いた気がするのですが、好評なようで良かったです。

* 成果として、Scala Play 2のサーバサイドアプリのレビューが可能になった、というのは想定していなかった部分ですが、お役に立てたようなら何よりです。

* Futureに関しては私はあまり手を出せていなかった部分ですが、「非同期処理の文脈を扱える」「for-comprehensionでフラットに書ける」などの部分が伝わっていたようなのは良かったです。

* 「型クラス」に関しては、正直ご期待に添えず申し訳ありませんでした。ただ、「型クラス」の紹介については、あくまでそういうものがあるよ、という話で、数学的な概念は関係なく便利な道具として使えるよ、というのが本来伝えたかったものではあります（その片鱗がimplicitの章にあります）。ともあれ、感想を全面的に反映するわけにはいきませんが、今後の参考にさせていただきます。

なお、私が公開部分の多くを執筆したこともあり、私が返答していますが、他に複数名の協力があり、本テキストが成り立っています（名前を出していいのかわからないのでここでは伏せますが）。ご感想、どうもありがとうございました。

**Comment by bleis-tift** [comment]
本文というより、ソース(markdown)の話なのですが、改行の仕方に統一感がないのが気になりました。
INTRODUCTION.mdでは文ですら改行されていませんが、sbt-install.mdでは文の途中でも改行されている、といった具合です。
前者は前者で差分表示の際につらい感じになるのですが、後者は出来上がるgitbookでみると文の途中に空白が入るので見栄えが悪いです。
最低限、句点では改行し、一文が長くなった場合は読点の位置でのみ改行する等のルールを設けた方がいいと思います。

また、明確な誤りではないものはこちらに書くようになっているように読めたのでここに書きますが、[sbt-install.md](https://github.com/dwango/scala_text/blob/739514dd20a9e4fb7293f125a667b1b4dc441ced/src/sbt-install.md)に「Windowsでの環境変数編集ツールとしては、 Rapid Environment Editorが非常に便利です。」とありました。
Windows10からはPATHを編集する程度であれば標準のもので十分に思えますので、この記述は不要ではないかと思うのですがいかがでしょうか。

**Comment by bleis-tift** [comment]
[control-syntax.md](https://github.com/dwango/scala_text/blob/daf85006396150fffaf43d575a1ae34037c379e5/src/control-syntax.md)のelseの省略についての説明で

> `Unit`型の値が補われたのと同じ値が返ってきます。

とありましたが、対象としている(とくにJavaプログラマ)は説明がなければわからないと思います。

**Comment by bleis-tift** [comment]
「明確な誤り」と「そうでない意見」とでPRかIssueへのコメントかを分けるのは面倒です。

**Comment by bleis-tift** [comment]
[control-syntax.md](https://github.com/dwango/scala_text/blob/daf85006396150fffaf43d575a1ae34037c379e5/src/control-syntax.md)のwhile式の説明で、

> なお、`break`文や`continue`文に相当するものはありません。

とありますが、breakやcontinueがしたくなった場合にどうするかということについて書いてあった方が親切だと思います。

**Comment by bleis-tift** [comment]
[control-syntax.md](https://github.com/dwango/scala_text/blob/daf85006396150fffaf43d575a1ae34037c379e5/src/control-syntax.md)のfor式の説明で、

> Scalaにはfor式という制御構文がありますが、これはJavaの制御構文と似た使い方ができるものの、全く異なる構文です。

とありますが、

Scalaにはfor式という制御構文がありますが、これはJavaの制御構文である拡張for文と似た使い方ができるものの、全く異なる構文です。

のようにどの構文と対応付いているのか明示したほうがいいと思います。
また、「全く異なる構文です」というのも言いすぎな気がします。
Scalaのfor式は、Javaの拡張for文のようにループのみに特化しておらず、より様々な制御に対応している構文という認識です。
あくまでループへの対応も様々な制御の一つであり、「全く異なっている」かというとそうでもないと思っています。

**Comment by bleis-tift** [comment]
[control-syntax.md](https://github.com/dwango/scala_text/blob/daf85006396150fffaf43d575a1ae34037c379e5/src/control-syntax.md)のmatch式の説明の書き出しが、

> `match`式は使い方によって非常に幅のある制御構造です。

となっており、直後を読めば分かるとはいえ、親切ではない(何も言っていないに等しい)と思います。
せめて、

`match`式は多分岐を行う制御構文ですが、Javaの`switch`文以上に様々なことができます。

のようにした方がより親切ではないでしょうか。

**Comment by bleis-tift** [comment]
[control-syntax.md](https://github.com/dwango/scala_text/blob/daf85006396150fffaf43d575a1ae34037c379e5/src/control-syntax.md)のmatch式の説明で、

> match式を使うときは、漏れがないようにするために、ワイルドカードパターンを使うことが多いです。

とありますが、これは出来る限り避けるべきプラクティスだと思います。
例えば、sealedなcase classが増えた時に、ワイルドカードパターンを使っているとコンパイラが指摘してくれなくなるため、できる限りワイルドカードパターンに頼らずに書くべきではないでしょうか。
もし、Javaのswitchとしてのmatchに限定した話であれば、それを明記したほうがいいと思います。

**Comment by bleis-tift** [comment]
[class.md](https://github.com/dwango/scala_text/blob/e4dd1053ada11c9350fa804306ae7abe27d20b79/src/class.md)の冒頭で、

> 最低限、Javaのクラスがわかっている事を前提にしますが、ご了承ください。

とありますが、[INTRODUCTION.md](https://github.com/dwango/scala_text/blob/b5a1acc22b3ef9f0b8673f0c792d6e170b25ef31/src/INTRODUCTION.md)では読者層として

> JavaやCなど、1つ以上のプログラミング言語の講習を受けている

とあります。
もしJavaのクラスの理解が必要なのであれば、INTRODUCTION.mdでそれを明らかにするべきでしょう。

**Comment by bleis-tift** [comment]
[class.md](https://github.com/dwango/scala_text/blob/e4dd1053ada11c9350fa804306ae7abe27d20b79/src/class.md)のクラス定義の説明で

> コンストラクタの引数をそのまま公開したい場合は、以下のように短く書くこともできます。

とありますが、「コンストラクタの引数をそのまま公開する」という表現はわかりにくいのではないでしょうか。

コンストラクタの引数と同名のフィールド(プロパティ？)を定義し、それを公開する場合は、以下のように短く書けます。

のような表現の方が分かりやすいと思います。

**Comment by bleis-tift** [comment]
[class.md](https://github.com/dwango/scala_text/blob/e4dd1053ada11c9350fa804306ae7abe27d20b79/src/class.md)のクラスの定義に

> クラス名の直後にコンストラクタの定義がある

とありますが、違和感があります。
クラス名の直後はコンストラクタの引数であって、定義の一部でしかないのではないでしょうか。

**Comment by bleis-tift** [comment]
[class.md](https://github.com/dwango/scala_text/blob/e4dd1053ada11c9350fa804306ae7abe27d20b79/src/class.md)のクラスの定義では、基本的にはScalaでは複数のコンストラクタは定義せず、プライマリコンストラクタしか使わない、というようなことが書いてあります。
それはそれでいいのですが、objectのapplyメソッドを定義したり複数オーバーロードしたりはするはずであり、「その代わり、objectのapplyメソッドとして定義することが多いです」のような脚注を入れた方がこれまで複数のコンストラクタを定義してきた人にとって引っかかりが起きにくいのではないでしょうか。
また、非プライマリなコンストラクタではなくobjectのapplyメソッドを使う理由(利点)もどこかに説明があると嬉しいです(こちらは個人的な興味ですが)。

**Comment by bleis-tift** [comment]
[class.md](https://github.com/dwango/scala_text/blob/e4dd1053ada11c9350fa804306ae7abe27d20b79/src/class.md)の複数の引数リストを持つメソッドですが、ここまでにコンストラクタを除いて1つの引数リスト内で複数の引数を使う例(実際のコード)が出てきていなかったように思います。
そのため、「Scalaでは複数引数のメソッドを定義するためには引数リストを使うのか」というような勘違いをさせてしまう恐れがあります。
addを2つのバージョンで書いて対比させたほうがいいのではないでしょうか。

**Comment by bleis-tift** [comment]
[class.md](https://github.com/dwango/scala_text/blob/e4dd1053ada11c9350fa804306ae7abe27d20b79/src/class.md)の継承の冒頭で

> クラスのもう1つの機能は、継承です。

とありますが、これより前で「クラスの1つの機能は～です」や、「クラスには2つの機能があります。まず最初の機能ですが」のような説明はなかったように思います。

**Comment by bleis-tift** [comment]
[object.md](https://github.com/dwango/scala_text/blob/5c5d90de5b68e1d6fa1340cf97c59d778b2243d6/src/object.md)の冒頭で

> `object`キーワードによって、同じ名前のシングルトンオブジェクトをグローバルな名前空間に1つ定義することができます。

とあります。
しかし、「グローバルな名前空間」というと無名パッケージを思い浮かべます(これはC#プログラマだからかもしれませんが)。

`object`キーワードによって、同じ名前のシングルトンオブジェクトを名前空間のメンバーとして定義し、それをJavaでの`static`メンバーの代わりとして使います。

のような表現の方が分かりやすいと思います。
さらに、「単なるstaticメンバーの代わりではない」というのも示せるとより良いですが、ここでする説明ではないようにも思います。

**Comment by bleis-tift** [comment]
[class.md](https://github.com/dwango/scala_text/blob/e4dd1053ada11c9350fa804306ae7abe27d20b79/src/class.md)に戻りますが、クラス定義の部分でコンストラクタ引数を取らない際のクラス定義方法について載っていません(かっこが省略できるやつです)。
`Adder`はそのスタイルで書いていますが、説明なしなのは不親切に思います。

そもそもの話として、構文の説明に使っている独自形式に説明も統一感もないのは問題だと思います。

**Comment by bleis-tift** [comment]
test

**Comment by kmizu** [comment]
> とありますが、breakやcontinueがしたくなった場合にどうするかということについて
> 書いてあった方が親切だと思います。

その直後でフォローするのは難しい（メソッド内メソッドを定義するとか、高階関数を使うとかいう話になるので）ですが、フォローできるかは検討してみます。

**Comment by kmizu** [comment]
> Windows10からはPATHを編集する程度であれば標準のもので十分に思えますので、この記述は
> 不要ではないかと思うのですがいかがでしょうか。

個人的には、Windows 10のでもまだめんどくさい印象があるのですが、標準でないツールを
あんまり入れさせるのはどうかという話はあるかなという気がしています。とりあえず、現状で
変更する程ではないかなと思っています。

**Comment by kmizu** [comment]
@bleis-tift さん

https://github.com/dwango/scala_text/issues/235#issuecomment-335213039

>  構文の説明に使っている独自形式に説明も統一感もないのは問題だと思います。

かなり対応が遅くなって申し訳ありませんが、新たに「記法」の章を設けて、構文の説明に使っている構文（メタ構文）について説明を追加し、それに従うように説明を書き直してみました。どうでしょうか？

**Comment by xuwei-k** [comment]
https://github.com/scala-text/scala_text/discussions

新機能のdiscussionsを試しに有効にしてみたけど、このissueはdiscussionsにconvertするか？ 🤔

**Comment by kmizu** [comment]
@xuwei-k あざます。とりあえず、discussionsに新たにトピック（？）立ててみました。

https://github.com/scala-text/scala_text/discussions/581

convertが自動でできそうにないなら、このリンクだけ貼ってcloseするのもありかなあと。

**Comment by xuwei-k** [comment]
convertは自動で出来るっぽいです。(右側の方)
おそらく、そういうことを意図して、issueやpull reqと、インクリメンタルされるidが共用みたいですし

![スクリーンショット 2020-12-11 1 10 51](https://user-images.githubusercontent.com/389787/101797759-baf3ea00-3b4d-11eb-80a4-2a302d339d2b.png)
