### ISSUE TITLE
継承について

### ISSUE THREAD

**Issue by bleis-tift** [scala-text/scala_text#339]
[class.md](https://github.com/dwango/scala_text/blob/e4dd1053ada11c9350fa804306ae7abe27d20b79/src/class.md)の継承の冒頭で

> クラスのもう1つの機能は、継承です。

とありますが、これより前で「クラスの1つの機能は～です」や、「クラスには2つの機能があります。まず最初の機能ですが」のような説明はなかったように思います。

また、この冒頭の説明全体がバラバラとした感じを受けます。

* 用語を説明なしに使っていて分かりにくい
    * 実装の再利用と処理の共通化の違いは？実装の再利用はスーパークラスに処理を共通化しているとみなせない？
* 説明があっちこっちに言っており、何が伝えたいことなのか分かりにくい
    * 「複数の実装の継承はメンバーの名前が衝突する場合の振舞いなどに問題がある」「Javaでは実装継承は1つまで」「Java8ではインターフェイスにデフォルト実装が持たせられる(ので複数の実装の継承ができるということが言いたい？でも本文中では何も言っていないし、前の文と矛盾する)」「Scalaではトレイトを使って複数の実装の継承ができる(後で説明するとしており、最初に述べた問題が解決されているかどうかの情報はここでは得られない)」
* 表現が分かりにくい
    * 「ここでは通常のScalaのクラスの継承について説明します(通常ではないScalaのクラスがある？通常ではない継承がある？通常の、に意味は特になく筆が滑っただけ？)」

**Comment by kmizu** [comment]
@bleis-tift だいぶ返信してなくてすいません。現在、scala_text を全体的に見直しているので、現時点での見解を回答します。

> 用語を説明なしに使っていて分かりにくい
> 実装の再利用と処理の共通化の違いは？実装の再利用はスーパークラスに処理を共通化していると
> みなせない？

この辺は前提知識としてJavaがある程度わかっているので、「実装の再利用」というワードで意図するところがわかってもらえるだろうという判断です。基本的にこのテキストは、最低Javaがちゃんとわかっていて、他の言語の経験もあるとなお良いくらいの読者を対象にしているので、用語を全部説明するのはやりすぎだと思っています（プログラミング入門書ならそれくらい慎重であるべきですが）。

> 説明があっちこっちに言っており、何が伝えたいことなのかわかりにくい

この点は改善したいと思っていますが、矛盾するというご指摘についてはちょっとよく理解しきれていないです。「Java 8ではインターフェイスにデフォルト実装が持たせられる」というのは最近のJavaを追えていない人向けの記述で、それ以上の意味はないのですが、そこが明示されていないのはよくなかったかもしれません。この辺はちょっと記述の仕方を変えてみます。

> 「Scalaではトレイトを使って複数の実装の継承ができる(後で説明するとしており、最初に述べた
> 問題が解決されているかどうかの情報はここでは得られない)」

この節ではトレイトの話が本題ではないのであとに回すことは許容していただければと思います。

> 表現が分かりにくい

これについては、ケースクラスの継承になると、構文が説明しているのとちょっと違ってしまうので、それを考慮して「通常の」という表現が入っています。実際、ケースクラスはScalaの中では若干特殊な扱いを受けています。正確さを期して、こういう表現を入れる癖があるのですが、それでわかりやすさを損なってしまうのは良くないので、ご指摘の点については脚注でケースクラスの継承について簡単に述べるようにします。

ただ、このテキストは全くの初学者向けではなくJavaを理解していてOOPもわかっていることを前提にしているので、実装の再利用といったOOPで普通に出てくる用語を説明なしに使っている点などはお許しいただければと思います。

**Comment by kmizu** [comment]
このあたり、JSAに委譲した現状では、色々改善の余地がありそうですが、新方針が決まっていないので、いったんcloseします cc: @bleis-tift
