### ISSUE TITLE
Scala 2.13 対応

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text#504]

**Comment by xuwei-k** [comment]
メモ https://twitter.com/xuwei_k/status/1178598121825112064

**Comment by xuwei-k** [comment]
tutがscala compilerに依存してて、2.13.0では動くけど、2.13.1では以下のエラーになる気がしてきた

```
java.lang.NoSuchMethodError: scala.tools.nsc.Settings.usejavacp()Lscala/tools/nsc/settings/AbsSettings$AbsSetting;
```

(もう少し調べて、確実にバグっぽかったら、tutにissueたてる)

**Comment by xuwei-k** [comment]
https://github.com/tpolecat/tut/issues/263 
さて、バグだとすると

- tutが対応されるまで2.13対応待つ
- 2.13.0なら動くっぽいので、tutに関しては2.13.0使いつつ、対応進めてしまう

のどっちか・・・

**Comment by xuwei-k** [comment]
厳しい… https://github.com/scalajp/scala_text/issues/522

**Comment by kmizu** [comment]
とりあえず、2.13対応は早めにやっちゃいたい気がするので、tutは2.13.0使っていったん対応進めるのもありではとちょっと思ってます。それでもって、 #522 にあるように mdoc で置き換えられるなら乗り換えるとか。
