### ISSUE TITLE
Scala学習テキストの方向性について

### ISSUE THREAD

**Issue by kmizu** [scala-text/scala_text#513]
当面、「Scala初学者向け」の改良を重視していく予定ですが、今後の方向性について何か意見があれば、どしどしこのissueで提案をいただければと思います。

**Comment by taisukeoe** [comment]
ドワンゴさんのorganizationのときのリンクから、今のリンク先へリダイレクトできない理由って何かあるんでしたっけ。
https://twitter.com/ncaq/status/1232634830807949313?s=19

**Comment by kmizu** [comment]
さっき、そちらの方にリプライしたんですが、  https://dwango.github.io/scala_text/  から https://scala-text.github.io/scala_text/　にリダイレクトされてる……はずです（手元のChromeでは）。

**Comment by kmizu** [comment]
https://twitter.com/kmizu/status/1232646977428439042 へのリプライをみると、どうも、 https://dwango.github.io/scala_text_previews/ が公開されちゃってたせいで検索エンジンを汚染してた案件ぽいです（以前、吉田さんが同じ事例を見かけてたような）。公開されて困るものじゃないんですが、検索エンジンの結果汚染しちゃって、研修テキストがない、と思われるのは困るので、ちょっと対策考えてみます。

**Comment by xuwei-k** [comment]
- https://github.com/scala-text/scala_text/issues/870 と被ってるというか、論点がよくわからない感がある(個別に議題があれば個別にissue立てて貰えばいい？)のでひとまずclose

**Comment by kmizu** [comment]
@xuwei-k 確かに。あざっす。
