### ISSUE TITLE
travis-ciでxenialからbionicへのアップデート

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text#516]
travis-ciは適当なubuntuのLTSを使うようになっている。

どうせそのうち必要になるので、(travis-ci側からの強制アップデートを待たずに)早めにやってしまってもいいかもしれない。
とはいえ、2019年の前半にtrustyからxenialに強制アップデートされたばかりなので、bionicに強制アップデートされるのは、xenialのサポートが完全に切れる頃？なので、そんなに急ぐ必要もないはず(たぶん・・・) https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment

以下、現時点で、必要だとわかっていること(これ以外にもあるかも？)

- https://github.com/scalajp/scala_text_pdf/pull/5 https://qiita.com/yyu/items/e0ed267df132795b7a5a openssl 1.1使う関係上deploy keyを登録し直す？
- https://twitter.com/xuwei_k/status/1178533028261318656 openjdk8と書くだけでは使えないっぽいので、jdk8を使い続けるなら、他のインストール方法にする。あるいはjdk11でビルドするように変えてしまう

**Comment by kmizu** [comment]
xenialのサポート期限が切れるのが2021年4月末なので、1年半以上はありますけど、来年末くらいにアップデートすればいいのかなと感じてますが、どうでしょう？（なんかbionicに早めにアップデートしとくと嬉しいことが多そうなら、早めにやるのもありかと思いますが）

**Comment by xuwei-k** [comment]
> bionicに早めにアップデートしとくと嬉しいこと

たしかに、いまのところあまりないですね。
上記の移行手順、pdfのほうのリポジトリでやったばかりなので、なれてるというか、忘れないうちにやれるくらい(?)

**Comment by xuwei-k** [comment]
逆にいうと、移行を遅らせるメリットもそれほど多くない(?)とも言えるが。
まぁ時間経った方が、もしjdk 8使い続けるなら、それのインストール方法の知見が世間的にたまってる、とかはあるか？

**Comment by xuwei-k** [comment]
Travis CIやめる方向だからcloseでいいかな
https://github.com/scala-text/scala_text/issues/574
