### ISSUE TITLE
google+ 死んだので消す

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text#517]
たぶんgitbookのなにかのplugin

![スクリーンショット 2019-10-01 15 51 57](https://user-images.githubusercontent.com/389787/65940429-79ed4980-e463-11e9-8716-c8a174a6d5d3.png)

**Comment by xuwei-k** [comment]
関連するかもしれないissue https://github.com/scalajp/scala_text/issues/518

**Comment by kmizu** [comment]
これ、 https://www.npmjs.com/package/gitbook-plugin-share かなと思ったんですが、どうもそれっぽい依存がないので、gitbook-cliが更新されない現在、放置するしかない気がしますね。

**Comment by xuwei-k** [comment]
gitbookからhonkitへ移行して、plugin自体動いてないのかわからないけど、表示はされてない
(代わりにTwitterとかも無くなってる？)気がするのでclose
