### ISSUE TITLE
gitbook-cliが更新されてない

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text#518]
https://github.com/scalajp/scala_text/issues/510#issuecomment-536430985

- 別の方法を探す？
- 大きな不都合が出てくるまで、このまま騙し騙しgitbook-cli使う？
- その他

**Comment by kmizu** [comment]
しばらくは騙し騙しgitbook-cliでいくとして、他に（フリーで使える）代替案としては、 https://github.com/kmuto/review がありそうです（Markdown使えないのがちょっとつらい）。Markdownが使える他のものがあれば、それに乗り換える方が変換コストかからなくていいですが。

**Comment by xuwei-k** [comment]
Scala界隈でよく使われてるのだと、こういうのはあるけど https://47deg.github.io/sbt-microsites/ 本というよりwebsite作る用っぽい(?)から、
epub作成とか、検索とか、各種pluginでの拡張とかがうまくできるのか謎、というのはある

**Comment by xuwei-k** [comment]
[tutはscala compilerに依存してて辛い](https://github.com/scalajp/scala_text/issues/504#issuecomment-536999179) というのはあるので、REPLでの出力が必要ないなら
https://github.com/lightbend/paradox
を使う、という手もあるな

**Comment by kmizu** [comment]
paradox はありかもと思いましたが、検索機能があるのかなという疑問が。全文検索は読む人的にはあった方がいいかなと思うので。

**Comment by xuwei-k** [comment]
はい。まぁ面倒なのでよほどいい代替えが見つかるか、積極的に置き換えやりたい人が現れない限り、しばらく今のままでいいか…という気持ち

**Comment by taisukeoe** [comment]
Rust製のgitbook likeなOSSあるみたいです。
https://github.com/rust-lang/mdBook

Rustの公式ドキュメントがmdBookで作られてるのですが、ザッと見た感じかなりgitbookに近そうです。検索機能とかもありますし。
https://doc.rust-lang.org/book/

**Comment by xuwei-k** [comment]
ここで教えてもらったけれど https://github.com/scala-text/scala_text/pull/564

https://github.com/honkit/honkit

メンテされなくなったgitbookをforkしてazuさんがメンテしてるやつがあるのか、ほほー

**Comment by xuwei-k** [comment]
GitHub Actions移行やるなら、これ障害になるかなぁ、どうだろう

**Comment by kmizu** [comment]
私も別経路で、honkit いいぽい話聞いたので、移行コストが最小で済むなら、そっちにしたい気持ちがあります。

**Comment by xuwei-k** [comment]
https://github.com/scala-text/scala_text/pull/589
