### ISSUE TITLE
ライセンスからNC条項の削除提案

### ISSUE THREAD

**Issue by EzoeRyou** [scala-text/scala_text#519]
ライセンスをCC-BY-NC-SA 3.0からCC-BY-SA 4.0に変更する提案。

ドワンゴからJSAに権利譲渡されたことにより、ライセンスにNon Commercialを入れておく理由はなくなった。

提案する変更は、`README.md`, `src/INTRODUCION.md`のライセンス表記を以下のように変更する。

```
本文書は、[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)

![CC-BY-SA](https://i.creativecommons.org/l/by-sa/4.0/88x31.png)

の元で配布されています。
```

また、慣習に従い、ルートディレクトリ直下に`LICENSE`というファイルを作成し、同様のライセンス表記を記述する。

**Comment by kmizu** [comment]
@EzoeRyou 
提案ありがとうございます。ただ、権利譲渡時に、3年間のライセンス維持という条件が入っています。先ほど、その件について、ドワンゴ側の責任者と改めて話したところ、NCを外すことについては異論はないものの、条件を変えて譲渡契約を再度結ぶのは割と手間がかかるよね、という感じになっています。というわけで、優先度低めでNCを外すことについて交渉や手続きなどを進められれば、と考えています。

**Comment by xuwei-k** [comment]
> ルートディレクトリ直下にLICENSEというファイル

本質とは関係ない余談として、これやってもいいかな、と、以前個人的に思ったけど、githubがcreative commonsのlicenceに関しては認識してくれなさそう(?)という気がして、じゃあ別にいいか、と勝手に思ったのでやってない。
が、(既存の記述消さないとしたら)記述が重複する程度のデメリットしかないので、やりたい人が多ければ、ルートディレクトリ直下に置くのはやってもいいかも

**Comment by y-yu** [comment]
これ https://github.com/scalajp/scala_text_pdf 側もあわせて変更するか。

**Comment by xuwei-k** [comment]
たしかに、もし変更するならpdf側も変更だろうけど、kmizuさんの言う通り面倒っぽいので、その決定待かなぁ

**Comment by xuwei-k** [comment]
> ドワンゴからJSAに権利譲渡されたことにより、ライセンスにNon Commercialを入れておく理由はなくなった

ところで、creative commonsの運用というか実例詳しくないので、単純に個人的な質問なんですが、一般的にわりとそういうものなんですか？
別にNon Commercial維持という選択肢も、それはそれで場合によってはありな気がするので

**Comment by kmizu** [comment]
> > ルートディレクトリ直下にLICENSEというファイル
> 
> 本質とは関係ない余談として、これやってもいいかな、と、以前個人的に思ったけど、githubがcreative commonsのlicenceに関しては認識してくれなさそう(?)という気がして、じゃあ別にいいか、と勝手に思ったのでやってない。
> が、(既存の記述消さないとしたら)記述が重複する程度のデメリットしかないので、やりたい人が多ければ、ルートディレクトリ直下に置くのは(licence変更関係なく)やってもいいかも

LICENSEファイルを入れるのは、わかりやすさ的にいいと思うので、やりましょか。

**Comment by xuwei-k** [comment]
Non Commercial 削るって、極端に言えば、誰かが多少内容変えて(変えなくても？) 有料で出版することなども可能になるということですかね・・・？

**Comment by kmizu** [comment]
> Non Commercial 削るって、極端に言えば、誰かが多少内容変えて(変えなくても？) 有料で出版することなども可能になるということですかね・・・？

極端な話としてはそうなるかと。その辺は、私は、たとえばMITライセンスで提供したOSSを組み込んだものを自由に販売できるのと同じように、そういう商売をしてくれてもいいや、とは思っています（NCを削っても、表示はしないといけないから、元が何かは明示される、はず、ですし）。

**Comment by EzoeRyou** [comment]
ShareAlikeを残せば、誰かが有料で販売したとしても、それもCC-BY-SAでライセンスされ、自由が保証される。

**Comment by kmizu** [comment]
また、あらためてNC条項の削除が必要ではという話が上がるまで、いったんcloseします
