### ISSUE TITLE
scalajpから他のscala_text専用organizationへ移行する？

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text#520]
https://github.com/scalajp/scala_text/issues/512#issuecomment-536933769

ひとまず移行するの決定なら、はやめにorganizationだけ作ってしまおうかと思うけど、idどれがいいですか？ (scala_textはアンダースコアが不可能)

- scala-text
- scalatext
- その他?

/cc @kmizu @taisukeoe

**Comment by xuwei-k** [comment]
private repo作りたくなったらscalajpのままのほうがそのまま使えて都合いい、というのはあるけど、おそらくprivate repoは必要ないはず(?)

**Comment by xuwei-k** [comment]
あと、さらに別organizationに移管するのって、(管理主体がJSAなら？)別にドワンゴ社との契約的には、すぐに実行しても特に問題ないんですよね？

(というかJSAのものになったなら、何しようがOKか・・・？)

**Comment by kmizu** [comment]
@xuwei-k はい。private repoは必要ないと思います。個人的には、scala-textがいいかなって気が。で、別organizationですが、おっしゃる通り、JSA主体なら問題ないです（契約的には別にgithubの何々organizationにとかはないので）。

**Comment by y-yu** [comment]
ちょっと割り込んでしまいますが、僕は`scalajp`にあってもいい気がします。このテキストを見た人にとって、そっちの方が誰が管理しているのかというところが分かりやすいという気がします。

**Comment by kmizu** [comment]
`scalajp` にあってもいいのはいいのですけど、`scalajp` は `ScalaMatsuri` の管理にも使ってるのでややこしいし、分けちゃった方がいいのでは感がやっぱりありますね。

**Comment by xuwei-k** [comment]
これどっちだろう・・・

https://github.com/organizations/new

![スクリーンショット 2019-10-01 19 51 39](https://user-images.githubusercontent.com/389787/65956247-eaf12900-e484-11e9-93af-3fed8e596b29.png)

**Comment by xuwei-k** [comment]
> 私がそもそもscalajp orgを作ったのですけど（記憶が若干曖昧ですけど、そうだったはず）、今はメインで管理してるのが

自分も記憶が曖昧ですけど、もともと `Japan Scala Users Group ` https://github.com/scalajp/scalajp.github.com というJSAとは別のゆるい団体用に作ったけど、そこにJSAやScala祭も乗っけた、みたいな経緯だった気がします

**Comment by kmizu** [comment]
> これどっちだろう・・・
> 
> https://github.com/organizations/new
> 
> ![スクリーンショット 2019-10-01 19 51 39](https://user-images.githubusercontent.com/389787/65956247-eaf12900-e484-11e9-93af-3fed8e596b29.png)

JSAが著作権持ってる形ではあるので、下の方で「Japan Scala Association」（？）ですかね（この名前はどう紐付けられるのだろう）。

**Comment by xuwei-k** [comment]
(user_idはやいもの順なので)
https://github.com/scala-text ひとまず作るだけ作った。使わなかったら消す(?)

**Comment by taisukeoe** [comment]
「どこが管理しているのか」については、organizationがscalajpじゃなくても、READMEで表明できるとは思うのですがどうでしょうか。

**Comment by kmizu** [comment]
作られた scala-text org、使うなら使うでサクサクと移行した方が忘れないで良さそうですが、どうします？移行良さそうなら、昼頃に

-  scala_text
- scala_text_pdf
- scala_text_previews
- S99

まとめてtransferします（このコメントに :+1 か :-1 もらえれば）。
cc: @xuwei-k @y-yu @taisukeoe

**Comment by xuwei-k** [comment]
移行するならするでいいけど、した後に細かい部分でいい感じリダイレクトされることを考慮するために、そこまで急ぐ必要無いと思うので、ちゃんと手順を決めてからにしたい。
scalajp側に再度forkしちゃうとリダイレクトされなくなるのでforkは作らないほうがいいが、gh-pagesだけリダイレクトさせるために、可能なら scalajp.github.io のリポジトリ作って、そっちでgh-pagesのリダイレクトの設定するとか

**Comment by kmizu** [comment]
@xuwei-k なるほど。確かに、リダイレクトされることを考慮した手順決めはやったほうがいいですね。いったん、それを決めてからにします。

**Comment by y-yu** [comment]
> 「どこが管理しているのか」については、organizationがscalajpじゃなくても、READMEで表明できるとは思うのですがどうでしょうか。

ふーむなるほどな。まあたしかにそれもそうか。ただ現状scala_textの情報がScalaMatsuriのブログに書かれるといった感じで、厳密な境界が曖昧（？）な雰囲気もあり、ここをしっかり別のリポジトリに分けておく必要もはたしてあるのかな？という気もするけど、単に引っ越し作業をまたやるのが面倒という気持ちなだけもしてきたので、すごく反対するわけでもないような気もしてきました。

**Comment by xuwei-k** [comment]
deploy keyはちゃんとtransferすればそのまま使えるっぽいので、あの作業は必要ないはずで、基本的にはやるなら `s/scalajp/scala-text/` の置換で済むはず・・・

**Comment by kmizu** [comment]
これ、ずっと放置するのもあれなので、ちょっと今日、リダイレクト実験とかやってみます。

**Comment by xuwei-k** [comment]
お、はい。自分の理想というか想像では、少し面倒だけど以前書いたこれ

> scalajp側に再度forkしちゃうとリダイレクトされなくなるのでforkは作らないほうがいいが、gh-pagesだけリダイレクトさせるために、可能なら scalajp.github.io のリポジトリ作って、そっちでgh-pagesのリダイレクトの設定する

が一番いい気がしているけど、最悪うまくいかなくても、まぁ移行することを優先するならいいか(?)

**Comment by xuwei-k** [comment]
`forkは作らないほうがいい` は、明示的にforkボタン押す、のに限らず、再生成でも(リダイレクトされなくなるという意味では)駄目、なはず

**Comment by kmizu** [comment]
とりあえず、

1. `scalajp/scala_text` を `scala-text/scala_text` にtransfer
2. `https://github.com/scalajp/scalajp.github.com` に リダイレクトの設定を書く 
  * https://superdevresources.com/redirects-jekyll-github-pages/ あたりを参考に
3. 適切にリダイレクトされるか確認
4. リダイレクトされてなければ、 `scalajp.github.com/scala_text/index.html` を作ってなんやかやする。
5. それでもリダイレクトされなければ、いったん戻す

という手順でやってみます。

**Comment by kmizu** [comment]
って、 scalajp.github.com 、jekyll 使ってないですね（気づいた）。index.htmlを直接書いてリダイレクトするのが速いかも。

**Comment by kmizu** [comment]
いったん、3相当までやって、 `http://scalajp.github.io/scala_text` がリダイレクトされることを確認したので、 他の関連リポジトリもtransferしていきます。

**Comment by kmizu** [comment]
- https://github.com/scala-text/scala_text
- https://github.com/scala-text/scala_text_pdf
- https://github.com/scala-text/S99
- https://github.com/scala-text/scala_text_previews

までtransferが完了＆＆リダイレクトを確認したので、リンク修正していきます。 cc: @xuwei-k @y-yu

**Comment by kmizu** [comment]
* 一通りリンク修正作業終わりった
* 何故か、travis-ciの方で、ビルドする設定がうまくできない（scala-textのownerが見つけられないと言われてしまう）
  * transferしたことがtravis-ci側に反映されるまで時間がかかる？(sync accountしても無理だった）
  * これ、何か原因がわかるようだったら、助けてもらえると。 to: @xuwei-k and/or @y-yu

**Comment by xuwei-k** [comment]
ありがとうございます。

自分もそれみてみたけど、たしかに何故かtravis-ci.orgで設定画面が出なくてよくわからんけど、ついでに `.com` のほうが設定できそうなら、そっちに移行するのもありかも・・・？

- https://qiita.com/nwtgck/items/da0e2f5ba2247403c2db
- https://qiita.com/ndxbn/items/784a5c41e36f8b824810

**Comment by kmizu** [comment]
なるほど。ちなみに、travis-ci.orgの件は、travis-ci上で、scala-text orgにアクセス権を与える操作をしていなかったせいっぽく、ビルドできるようになりました。

**Comment by xuwei-k** [comment]
travisも動いたし、だいたい終わったはずなのでcloseで
