### ISSUE TITLE
tutがもうメンテナンスされない？

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text#522]
https://github.com/tpolecat/tut/commit/49383af8de7e0046e3dc27afdaab870cf1fee4c3

**Comment by kmizu** [comment]
なんと…

**Comment by xuwei-k** [comment]
forkしてメンテしようかなぁ

**Comment by xuwei-k** [comment]
いや、試さないとわからないけど、mdocがわりとそのまま代替えになるなら乗り換えか？

https://scalameta.org/mdoc/docs/tut.html

**Comment by xuwei-k** [comment]
https://github.com/typelevel/cats-effect/commit/a638c2385e5ac27c937bfaefcb4062364235dbf6

他のprojectでのtutからmdocへの移行例

**Comment by xuwei-k** [comment]
mdocもscala-compilerに依存してるのか
https://github.com/scalameta/mdoc/blob/908f569d074502e769f90368f01ff4c2090af4e9/mdoc/src/main/scala/mdoc/internal/markdown/MarkdownCompiler.scala#L26-L29

**Comment by kmizu** [comment]
えいやっと、mdoc対応進めちゃいますかね…

**Comment by xuwei-k** [comment]
https://github.com/scala-text/scala_text/pulls
