### ISSUE TITLE
パターンマッチによる値の取り出しのサンプルコードインデントずれ

### ISSUE THREAD

**Issue by kazuki5555** [scala-text/scala_text#544]
## URL

- https://scala-text.github.io/scala_text/control-syntax.html#%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3%E3%83%9E%E3%83%83%E3%83%81%E3%81%AB%E3%82%88%E3%82%8B%E5%80%A4%E3%81%AE%E5%8F%96%E3%82%8A%E5%87%BA%E3%81%97

```
val lst = List(List("A"), List("B", "C"))
// lst: List[List[String]] = List(List("A"), List("B", "C"))

lst match {
  case List(a@List("A"), x) =>
  println(a)
  println(x)
  case _ => println("nothing")
}
// List(A)
// List(B, C)
```

- 1学習者としてこちらを利用させて頂いているさいに、こちらのインデントずれが気になりました。

**Comment by kmizu** [comment]
こちらで修正済み（？） https://github.com/scala-text/scala_text/pull/545 なので閉じます。ありがとうございます。

**Comment by kazuki5555** [comment]
issueとPRがうまく紐づけられていなかったようですみません。ありがとうございます。
