### ISSUE TITLE
[Contents] Early Definitions(early initializers?)に関する記述を削除する

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text#552]
trait.mdに

> トレイトの`val`の初期化順序を回避するもう1つの方法としては事前定義（Early Definitions）を使う方法もあります

という説明がある。以下のような警告がでる

```
warning: /Users/kenji/scala-text/scala_text/src/trait.md:391:17: early initializers are deprecated; they will be replaced by trait parameters in 2.14, see the migration guide on avoiding var/val in traits.
class C extends {
                ^
```

非推奨なのはScala 2.13から？

記述を消すか、非推奨なことを説明する？

**Comment by kmizu** [comment]
@xuwei-k これ、もう消しちゃいましょうか。Scala 3でも消えることですし。

**Comment by xuwei-k** [comment]
単純に消すか、言及しつつ、同じことをしたい場合の説明(trait parameterだっけ？)を追加するか、みたいな選択肢…

**Comment by xuwei-k** [comment]
- https://github.com/scala-text/scala_text/commit/c08b721841a42b04399d9f2fdce0e8a4adf8f040#diff-452948212d2404fc9782800c05a38c438a24f38abf4a12220e636fc5ec13a5b9R387

**Comment by kmizu** [comment]
2022/07/04（月）のもくもく会で決まったこと
- 単純に消す（現状のScalaでもほぼ使わないので）

**Comment by xuwei-k** [comment]
- https://github.com/scala-text/scala_text/pull/980
