### ISSUE TITLE
Scala 2.13.4

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text#560]

**Comment by kmizu** [comment]
これって、どういう意図でしたっけ？（なんか、mdocかなんかの問題関連だったような記憶が）

**Comment by xuwei-k** [comment]
いや別に難しくないけど、標準ライブラリのリンクの行番号とか含め確認しながら置換が面倒でやってないだけです

**Comment by xuwei-k** [comment]
https://github.com/scala-text/scala_text/commit/06a3beea26af0202dc19eb4b8f2f272758c04694
