### ISSUE TITLE
テスト説明コメントの誤字

### ISSUE THREAD

**Issue by TakaK22** [scala-text/scala_text#561]
https://scala-text.github.io/scala_text/test.html

`src/main/scala/Calc.scala` sum関数の説明コメントに誤りがあります。
>   /** 整数の配列を取得し、それらを出し合わせた整数を返す 

`を足し合わせた〜 `が正しいと思われます。

**Comment by y-yu** [comment]
@TakaK22 

報告ありがとうございます。修正をマージしたのでcloseしました。
