### ISSUE TITLE
homebrewでsbtをインストールすることに関する注意点の記述追加(あるいはbrewを非推奨？)

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text#566]
以下にあるように、デフォルトでは、LTSではない一番新しいopenjdkを持ってきてしまう可能性があるらしい？ので、その件に関する記述を追加するか、brewでのインストールは非推奨にしたほうがいいかもしれない？

https://github.com/Homebrew/homebrew-core/issues/50649

http://eed3si9n.com/ja/sbt-1.3.12

> #### Homebrew に関する注意
> Homebrew のメンテナはもっと brew 依存性を使いたいという理由で JDK 13 への依存性を追加した brew#50649。そのため、PATH が通っている java が JDK 8 や 11 であっても sbt が JDK 13 で実行されるようになってしまう。
>
> sbt が JDK 13 で実行するのを回避するには jEnv をインストールするか、SDKMAN に乗り換える必要がある。

**Comment by xuwei-k** [comment]
面倒ならこのissueのリンクだけとりあえず貼るか？(ぇ

**Comment by saka1** [comment]
これ先日踏んじゃったので、一言ぐらい注意書きがあった方が嬉しいとは思いました 👍

**Comment by xuwei-k** [comment]
https://github.com/scala-text/scala_text/commit/dc7b91066280e3129b823fb78ac46c9b4f10bf49
