### ISSUE TITLE
GitHub Actionsへ移行？

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text#574]
- https://xuwei-k.hatenablog.com/entry/2020/11/04/161400
- https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

organization単位でこの程度の使い方なら、すぐに制約に達することもなさそう？だが、(移行が面倒、という理由以外で)Travis CIを使い続ける積極的な理由がないならば、移行を考えてもいいかもしれない？

**Comment by y-yu** [comment]
急ぐ必要はないと思いますけど、僕もGitHub Actionsへの移行に賛成です。

**Comment by xuwei-k** [comment]
https://github.com/scala-text/S99/commit/464911ff9ad34a21b06c7303998e1ad18c28df07
S99は移行した

この方法でscala-steward設定した
https://xuwei-k.hatenablog.com/entry/2020/11/21/035306
https://github.com/scala-text/S99/commit/b9a5109f1a501d8b9241d2cb858b884011e53b93

**Comment by xuwei-k** [comment]
特に他に意見なければ、そのうちGitHub Actionsに変えます。
他のリポジトリでだいぶTravis CIからGitHub Actionsへの移行経験積んだので、たぶんいける気がするな。
(簡単そうなやつからやって、難しいというか、面倒そうなこれは後回しにしていた)

**Comment by kmizu** [comment]
反応遅れました。 👍  です。
