### ISSUE TITLE
discord

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text#854]
のリンクを、readmeかどこかに貼る?
誰でも入れるようにするのか、招待制なのか？

**Comment by xuwei-k** [comment]
そもそも議論の場所散らばるのがデメリットあるというか、あまり活発でなくリアルタイム性がそれほど必要ないのなら、単にGitHub上で全部完結ですらいい可能性あるけど、使い分けどうするんだ…discussionsも有効にしてあるが。

gitteそのものが使いづらかった側面はあるかもしれないけど、大抵のそれほど大規模ではないOSSでは結局gitterが放置されがちになった気はするし

**Comment by xuwei-k** [comment]
コンテキストとしては、そもそもミーティングきっかけに使い始めたけど、運用方針が決まってない(ように見える)というか、discordの存在すらわからない可能性が高い状態である、ことが微妙、という問題提起

https://connpass.com/event/240192/

**Comment by xuwei-k** [comment]
とりあえずREADMEにリンクは貼ったんで、必要ならもっと記述追加するなどはしつつ、細かい使い分けどうするのかはともかく、
今のところ、使い続ける方向性になりそう、というメモ

**Comment by kmizu** [comment]
（もくもく会中）いったんまとまったぽいのでcloseします。
