### ISSUE TITLE
GitHub Actionsの自動update

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text#855]
https://github.com/scala-text/scala_text/commit/b269309a921906e401c1da02f246135e2c922e32
https://github.com/scala-text/scala_text/commit/8a0f5af8411b16d631bde47814ca92488e755252

github-pages-deploy-action 互換ないのに上げる事故があったから、一旦無効化したが、再度有効化するかどうか

**Comment by kmizu** [comment]
これどうしましょうかね。再度有効化すると壊れそうなので当面放置って感じにしときたい感じも。
