### ISSUE TITLE
[Outdated] scalastyle -> scalafix+scalafmt

### ISSUE THREAD

**Issue by i10416** [scala-text/scala_text#857]
https://github.com/scala-text/scala_text/blob/master/src/test.md#%E3%82%B3%E3%83%BC%E3%83%89%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF

**Comment by xuwei-k** [comment]
scalastyleはScala 3ではオワコンっぽいのはそうなんだけど、scalafmtにないような機能もあった気がする(うろ覚え)ので、場合によっては他のlinter的なものにも軽く言及する…？

**Comment by xuwei-k** [comment]
wartremoverはメンテされてるというか、自分だけがやってるけど、そもそも今のままじゃScala 3で動かないんで…

**Comment by i10416** [comment]
> wartremoverはメンテされてるというか、自分だけがやってるけど、そもそも今のままじゃScala 3で動かないんで…

ハエッ😇 そうだったんですか...

となると scalafix の rules と scalafmtのfmtcheck あたりに言及しますか...

**Comment by xuwei-k** [comment]
https://scalacenter.github.io/scalafix/docs/users/related-projects.html

scalafix公式に書いてある、各種linterの比較？解説？記事

**Comment by xuwei-k** [comment]
https://xuwei-k.github.io/slides/wartremover-3/#1

wartremoverは動くようになる予定

**Comment by i10416** [comment]
👀

**Comment by i10416** [comment]
close します、

**Comment by i10416** [comment]
databricksのプロダクトが意外とScalastyleを使ってておやおや🤔という顔になった
