### ISSUE TITLE
[Outdated] Scala IDE for Eclipse の記述は必要？

### ISSUE THREAD

**Issue by i10416** [scala-text/scala_text#862]
> IntelliJ IDEA + Scala Pluginと Scala IDE for Eclipseの2種類がありますが

Scala IDE for Eclipse よりも VS Code + Metals について言及するほうがいいかもしれない

**Comment by i10416** [comment]
> あれ多少消した気がしたけど、まだ残ってたのかな

https://github.com/scala-text/scala_text/commit/40e7e6c20020eb4fcfb566e90b1a5c7570783b4b は把握してましたが IDE のページで冒頭にちょろっと言及されてますね.

**Comment by i10416** [comment]
最近は Metals もだいぶ安定していて使い勝手もいいので IDE の章を Editor & IDE に書き換えたほうがよさそうですね。(特に Java を使ったことがないユーザーは JetBrains 製品よりも VS Code や魔改造した Vim のほうがなじみがあるはずなので.)

**Comment by xuwei-k** [comment]
- https://github.com/scala-text/scala_text/pull/876

**Comment by kmizu** [comment]
既に修正されたのでclose
