### ISSUE TITLE
scala-sandboxリポジトリどうする

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text#865]
https://github.com/scala-text/scala-sandbox

本文で言及されてるが、このissue作成時点で、数年間放置されてる。

使わない(メンテしない？Scala公式g8使うか、本文に全部書くか？、あるいは…)なら、アーカイブして本文からの参照削除。

メンテするならscala-steward設定するか?
でも、サンプル内部にscala-stewadのconfigあると「何これ？？？」ってなるなら、手動メンテするか(手動メンテは厳しすぎる気がする？)

**Comment by i10416** [comment]
これくらいの内容ならわざわざプロジェクトを用意しなくてもいいのでは？
tree コマンドでディレクトリ構成を表示したものが本文にあれば伝わると思います.

```scala
object HelloWorld {
  def main(args: Array[String]): Unit = {
    println("Hello, World!")
  }
}
```

**Comment by xuwei-k** [comment]
ci設定した
