### ISSUE TITLE
[Outdated] rapid environment editor の記述を消す

### ISSUE THREAD

**Issue by i10416** [scala-text/scala_text#869]
https://github.com/scala-text/scala_text/blob/master/src/sbt-install.md#windows%E3%81%AE%E5%A0%B4%E5%90%88
> Windowsでの環境変数編集ツールとしては、 Rapid Environment Editorが非常に便利です

REE 更新されてないので消して良さそう

Latest version
Jul 3, 2018
https://www.rapidee.com/ja/about

https://github.com/scala-text/scala_text/discussions/235#discussioncomment-187201

**Comment by kmizu** [comment]
@i10416 確かに。pull req作成お願いしてしまっていいですか？
