### ISSUE TITLE
デフォルトbranchの名前をmasterから変える？

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text#874]
わりとどうでもいいというか、個人的にそれほどこだわり無いけれど、もし変えるなら早めのほうがいい？ので、一応意見募集するために話題を出しておく。
masterから、mainにするか、あるいは他の案(developとか？)か、変えたい人がほぼいなければ、今まで通りmasterを維持か？

**Comment by rinotc** [comment]
自分も特にこだわりないですね。。

**Comment by xuwei-k** [comment]
特に意見でないからこのままcloseかなぁ
