### ISSUE TITLE
[Contents] Javaのインストール方法に関する記述を追加する

### ISSUE THREAD

**Issue by rinotc** [scala-text/scala_text#877]
今は省略されてる。

#870 より

> Javaを習得済みを前提にしない方向へ

なので、Javaのインストール方法の記述も必要かなと。

**Comment by i10416** [comment]
> Javaのインストール方法の記述も必要かな

同意。しかしJavaのインストール方法は色々あるのでどれをのせるのがいいんでしょう🤔

**Comment by xuwei-k** [comment]
すぐには変化はしないけど、でも数年単位で流行が変わったりするのと、普通のソフトウエアと違って記述が古くなってることをテストする手段が基本ないから(Javaのインストール方法に限らないけど)、
とりあえず記述すること自体は簡単なんだけど、最悪の場合その記述のせいでつまずいたら逆効果でさえあるから、わりと責任というか考慮が必要(or ちゃんとメンテする覚悟が必要)ではある…
がまぁこのテキスト自体がそこから頑張っていく方針ならやるしかない…(?)

**Comment by rinotc** [comment]
> しかしJavaのインストール方法は色々あるのでどれをのせるのがいいんでしょう🤔

sdkman!でいいかなと思ってました。

> 数年単位で流行が変わったりするのと、普通のソフトウエアと違って記述が古くなってることをテストする手段が基本ない

んー。。確かに。。

テキストの中に、「記述が古い？」リンクを作って古いと感じたらissueをたててもらうようにするとか？

**Comment by kmizu** [comment]
2022/7/4のもくもく会で決まったこと
- sdkman!を使った記述に修正
- @rinotc にアサイン

**Comment by rinotc** [comment]
修正mergeしたのでクローズします。
