### ISSUE TITLE
override キーワードを外した時のコンパイルエラーメッセージ例がない

### ISSUE THREAD

**Issue by rinotc** [scala-text/scala_text#983]
> ここで`override`キーワードをはずすと、次のようにメッセージを出力して、**コンパイルエラー**になります。 

の部分の「次のようにエラーメッセージ」のエラーメッセージがないな 🤔

_Originally posted by @rinotc in https://github.com/scala-text/scala_text/issues/981#issuecomment-1201386887_

## 概要

以下の部分でコンパイルエラーメッセージ例があるように示唆される文章があるが、ない。

https://github.com/scala-text/scala_text/blob/19e9a87e8360e7c799c460847bccc5a91148413f/src/class.md?plain=1#L213-L221

**Comment by xuwei-k** [comment]
- https://github.com/scala-text/scala_text/issues/550

**Comment by kmizu** [comment]
@xuwei-k mdocの改善関係は時間かかりそうなので、いったんメッセージ例埋め込んじゃおうと思います（ @rinotc さんにアサインしました）。
