### ISSUE TITLE
[Contents] implicit parameter の使い所の説明がほしい

### ISSUE THREAD

**Issue by rinotc** [scala-text/scala_text#989]
業務で `implicit parameter` の使い所がちょっと違うなぁって思うことがあるんですが、それを言語化できないなと思ったので、暗黙パラメータで引回すものの代表的な基準とか、良くない使い方とかの説明があると嬉しいかも 🤔

**Comment by xuwei-k** [comment]
良い悪いは、場合によるというか文化やそれぞれの規約にもよるし、うまく書くのはかなり難しそうな。
まず書くとしたら、型クラスとしてと、コンテキスト引き回しと、(良し悪しはあえて深く触れずに？)いくつか種類というかパターンがあることを説明…? 🤔 

あとScala 3でそのあたりの見た目が結構変わるしなぁ

**Comment by kmizu** [comment]
@xuwei-k 確かに難しいとこですね。で、 @rinotc さんと今さっき話してたんですが、implicit defで多相的な型クラスを使うケースについての説明が足りてないとのことでした。なので、「型クラスの誘い】に加筆する方向で可能かもしれません。

**Comment by Javakky** [comment]
> Abtracting over contextual information. [Using clauses](https://docs.scala-lang.org/scala3/reference/contextual/using-clauses.html)を使って呼び出し時に利用可能で、暗黙に引き渡されるべき情報を抽象化することができる。Scala 2 からの改善としては、using 節が型だけで指定できるようになったことが挙げられる。 これによって明示的に参照されることのない関数の引数に命名する必要がなくなった。
> Providing Type-class instances. [Given instances](https://docs.scala-lang.org/scala3/reference/contextual/givens.html) を使ってある型に対応する canonical value を定義することができる。実装を公開することなく、型クラスを使ったプログラミングをよりわかりやすく書ける。
> 
> Retroactively extending classes. Scala 2 では拡張メソッドは暗黙の変換か implicit classを使って書くことができた. 一方 Scala 3 では [extension methods](https://docs.scala-lang.org/scala3/reference/contextual/extension-methods.html) が直接的に言語仕様に含まれているのでよりわかりやすいエラーメッセージを表示できる。型推論も改善された。
> Viewing one type as another. 暗黙の変換は型クラスConversionのインスタンスとしてゼロから [再設計](https://docs.scala-lang.org/scala3/reference/contextual/conversions.html)された。
Higher-order contextual abstractions. 全く新しい機能である [context functions](https://docs.scala-lang.org/scala3/reference/contextual/context-functions.html) は暗黙の引数をとる関数型を第一級オブジェクトとして扱う。この機能はライブラリ作者にとって重要である。また、簡潔なドメイン特化言語(DSL)を記述するのにも役立つ。
> 
> Actionable feedback from the compiler. コンパイラが暗黙の引数の解決に失敗した場合、解決に役立つ [import suggestions](https://www.scala-lang.org/blog/2020/05/05/scala-3-import-suggestions.html) を提示する。

https://docs.scala-lang.org/ja/scala3/new-in-scala3.html

**Comment by kmizu** [comment]
@Javakky @rinotc 提案ですけど、現状は実装というか仕様ベースの書き方になっているわけですが、

1. 暗黙の型変換
2. 拡張メソッド
3. 文脈引き渡しパターン
4. 型クラス（パターン）

の4つくらいの「使い方」があるという感じで、意図を中心に説明するとすっきりしそうです。という感じでどうでしょうか？ cc @xuwei-k

**Comment by kmizu** [comment]
ラフ案としては、

```
Scalaにはimlicitというキーワードがあります。このキーワードは実際には複数の使われ方をするので、初学者はしばしば混乱するのですが、大別すると以下の4つの使い方に分かれます。

1. 暗黙の型変換
1. 拡張メソッド
1. 文脈引き渡し
1. 型クラス

以降、これらの使い方について説明していきます
```

みたいな感じで。

**Comment by kmizu** [comment]
@kmizu にアサイン。Scala 3のこともちょっと追記予定。
