### ISSUE TITLE
変位指定は難しいので注意して使う旨の記述を追加する

### ISSUE THREAD

**Issue by youta32449999** [scala-text/scala_text#991]

**Comment by kmizu** [comment]
＋アルファの話として：変異指定は読めれば大体のケースで十分だよみたいなこともお願いします。

**Comment by xuwei-k** [comment]
変異指定は難しい、から変に使おうとしてミスするくらいなら使わない方がいい(?)、くらいな方針には同意だけど、
`ライブラリ書く人` と `プロダクトコードを書く人` という分け方には割と違和感あるかなぁ🤔

文化や慣習やその他色々によってはライブラリでも使わないパターン逆に普通あるし、その逆でプロダクトコードでも必要なら普通に使うし

**Comment by kmizu** [comment]
なるほど。確かに、区分けとしてその二つは良くなかったかもしれません。変異指定は難しいので、

- まずは読めることが重要
- 使いこなすのは難しいので、自作のクラスで使う場合には慎重に

くらいでどうでしょうか？

**Comment by xuwei-k** [comment]
そうですね 🙆‍♂️
