### ISSUE TITLE
ケースクラスとパターンマッチングでDayOfWeek型のmatch式でSaturdayのケースが漏れている

### ISSUE THREAD

**Issue by youta32449999** [scala-text/scala_text#998]
`sealed`によるmatch式網羅性の警告を表示させるために`Saturday`を意図的に外しているのでしょうか?

**Comment by youta32449999** [comment]
網羅した例を掲載して警告は自分で抜いて確かめてねという場合と
```scala
x match {
  case Sunday => 1
  case Monday => 2
  case Tuesday => 3
  case Wednesday => 4
  case Thursday => 5
  case Friday => 6
  case Saturday => 7
}
```
意図的にSaturdayを抜いたから警告が出るのを確かめてねの
```scala
x match {
  case Sunday => 1
  case Monday => 2
  case Tuesday => 3
  case Wednesday => 4
  case Thursday => 5
  case Friday => 6
  // Saturdayのcaseが漏れているため警告が出る
}
```
上記2パターンのどちらかが良い気がします。

**Comment by xuwei-k** [comment]
他のやつにも何度も貼ってるけど、たぶんこれのせいで不自然に見えてる気がするので、これを根本的にさっさと解決したい

- https://github.com/scala-text/scala_text/issues/550

**Comment by youta32449999** [comment]
本来は警告が見えていたのですね。。

**Comment by kmizu** [comment]
@youta32449999 これ、見た目の問題もありますが、文章自体が

> これは、xがSundayなら1を、Mondayなら2を…返すパターンマッチです。ここで、パターンマッチで漏れがあった場合、コンパイラが警告してくれます。

となっていて、「漏れがあった場合」という記述がややこしいですね。

> xがSundayなら1を、Mondayなら2を…返すパターンマッチです。ここで、Sundayに対する場合分けが記述されていませんが、その時はコンパイラが警告してくれます。

（ここで、現状警告が見えていないので、直に貼ってしまいたい）

という感じでどうでしょうか。

**Comment by kmizu** [comment]
マージされたので close。
